### ISSUE TITLE
Clipboard monitor process occasionally crashes when selecting text on Plasma Wayland

### ISSUE THREAD

**Issue by hexchain** [hluk/CopyQ#2151]
**Describe the bug**
On Plasma Wayland, one of the processes occasionally crashes when selecting text. It isn't always reproducible but usually happens with X11 Electron applications.

**To Reproduce**
Select some text in an X11 application.

**Expected behavior**
Nothing should happen.

**Version, OS and Environment**
CopyQ Clipboard Manager 6.3.2
Qt: 5.15.6
KNotifications: 5.98.0
Compiler: GCC
Arch: x86_64-little_endian-lp64
OS: Arch Linux

**Additional context**
Backtrace:
<details>

```
Core was generated by `/usr/bin/copyq --clipboard-access monitorClipboard'.
Program terminated with signal SIGSEGV, Segmentation fault.
(gdb) info threads
  Id   Target Id                        Frame
* 1    Thread 0x7f1615682840 (LWP 3783) 0x00007f16191f50ce in std::__atomic_base<QtSharedPointer::ExternalRefCountData*>::load (__m=std::memory_order_relaxed, this=<optimized out>)
    at /usr/include/c++/12.2.0/bits/atomic_base.h:820
  2    Thread 0x7f1607e236c0 (LWP 3820) __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x55f5b161b4c8) at futex-internal.c:57
  3    Thread 0x7f160ebf36c0 (LWP 3805) 0x00007f1618ca80bf in __GI___poll (fds=fds@entry=0x7f160ebf2d30, nfds=nfds@entry=2, timeout=timeout@entry=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  4    Thread 0x7f1614f8d6c0 (LWP 3796) 0x00007f1618ca80bf in __GI___poll (fds=0x7f16100053e0, nfds=3, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  5    Thread 0x7f160e3f26c0 (LWP 3807) 0x00007f1618ca80bf in __GI___poll (fds=fds@entry=0x7f160e3f1d30, nfds=nfds@entry=2, timeout=timeout@entry=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  6    Thread 0x7f16064df6c0 (LWP 3824) __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x55f5b161a518) at futex-internal.c:57
  7    Thread 0x7f1606ce06c0 (LWP 3823) __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x55f5b1619fac) at futex-internal.c:57
  8    Thread 0x7f16074e16c0 (LWP 3822) __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x55f5b1695698) at futex-internal.c:57
(gdb) thr apply all bt

Thread 8 (Thread 0x7f16074e16c0 (LWP 3822)):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x55f5b1695698) at futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x55f5b1695698, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at futex-internal.c:87
#2  0x00007f1618c3051f in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x55f5b1695698, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at futex-internal.c:139
#3  0x00007f1618c32cd0 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55f5b1695648, cond=0x55f5b1695670) at pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x55f5b1695670, mutex=0x55f5b1695648) at pthread_cond_wait.c:618
#5  0x00007f160c20399e in cnd_wait () at ../mesa-22.2.2/src/c11/impl/threads_posix.c:135
#6  0x00007f160c1b6f8c in util_queue_thread_func () at ../mesa-22.2.2/src/util/u_queue.c:287
#7  0x00007f160c2038cc in impl_thrd_routine () at ../mesa-22.2.2/src/c11/impl/threads_posix.c:67
#8  0x00007f1618c338fd in start_thread (arg=<optimized out>) at pthread_create.c:442
#9  0x00007f1618cb5a60 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 7 (Thread 0x7f1606ce06c0 (LWP 3823)):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x55f5b1619fac) at futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x55f5b1619fac, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at futex-internal.c:87
#2  0x00007f1618c3051f in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x55f5b1619fac, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at futex-internal.c:139
#3  0x00007f1618c32cd0 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55f5b1619f58, cond=0x55f5b1619f80) at pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x55f5b1619f80, mutex=0x55f5b1619f58) at pthread_cond_wait.c:618
#5  0x00007f160c20399e in cnd_wait () at ../mesa-22.2.2/src/c11/impl/threads_posix.c:135
#6  0x00007f160c1b6f8c in util_queue_thread_func () at ../mesa-22.2.2/src/util/u_queue.c:287
#7  0x00007f160c2038cc in impl_thrd_routine () at ../mesa-22.2.2/src/c11/impl/threads_posix.c:67
#8  0x00007f1618c338fd in start_thread (arg=<optimized out>) at pthread_create.c:442
#9  0x00007f1618cb5a60 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 6 (Thread 0x7f16064df6c0 (LWP 3824)):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x55f5b161a518) at futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x55f5b161a518, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at futex-internal.c:87
#2  0x00007f1618c3051f in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x55f5b161a518, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at futex-internal.c:139
#3  0x00007f1618c32cd0 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55f5b161a4c8, cond=0x55f5b161a4f0) at pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x55f5b161a4f0, mutex=0x55f5b161a4c8) at pthread_cond_wait.c:618
#5  0x00007f160c20399e in cnd_wait () at ../mesa-22.2.2/src/c11/impl/threads_posix.c:135
#6  0x00007f160c1b6f8c in util_queue_thread_func () at ../mesa-22.2.2/src/util/u_queue.c:287
#7  0x00007f160c2038cc in impl_thrd_routine () at ../mesa-22.2.2/src/c11/impl/threads_posix.c:67
#8  0x00007f1618c338fd in start_thread (arg=<optimized out>) at pthread_create.c:442
#9  0x00007f1618cb5a60 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 5 (Thread 0x7f160e3f26c0 (LWP 3807)):
#0  0x00007f1618ca80bf in __GI___poll (fds=fds@entry=0x7f160e3f1d30, nfds=nfds@entry=2, timeout=timeout@entry=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f161a50cc7d in poll (__timeout=-1, __nfds=2, __fds=0x7f160e3f1d30) at /usr/include/bits/poll2.h:39
#2  QtWaylandClient::EventThread::run (this=0x55f5b1555480) at /usr/src/debug/qtwayland/src/client/qwaylanddisplay.cpp:208
#3  0x00007f16191b92ba in QThreadPrivate::start (arg=0x55f5b1555480) at thread/qthread_unix.cpp:330
#4  0x00007f1618c338fd in start_thread (arg=<optimized out>) at pthread_create.c:442
#5  0x00007f1618cb5a60 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 4 (Thread 0x7f1614f8d6c0 (LWP 3796)):
#0  0x00007f1618ca80bf in __GI___poll (fds=0x7f16100053e0, nfds=3, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f161875fe2f in g_main_context_poll (priority=<optimized out>, n_fds=3, fds=0x7f16100053e0, timeout=<optimized out>, context=0x7f1610001cf0) at ../glib/glib/gmain.c:4543
#2  g_main_context_iterate.constprop.0 (context=0x7f1610001cf0, block=1, dispatch=1, self=<optimized out>) at ../glib/glib/gmain.c:4233
#3  0x00007f16187080d2 in g_main_context_iteration (context=0x7f1610001cf0, may_block=1) at ../glib/glib/gmain.c:4303
#4  0x00007f16193ac50c in QEventDispatcherGlib::processEvents (this=0x7f1610000b70, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#5  0x00007f161935a32c in QEventLoop::exec (this=0x7f1614f8cd10, flags=...) at ../../include/QtCore/../../src/corelib/global/qflags.h:69
#6  0x00007f16191bc49f in QThread::exec (this=this@entry=0x7f16189f7560 <(anonymous namespace)::Q_QGS__q_manager::innerFunction()::holder>) at ../../include/QtCore/../../src/corelib/global/qflags.h:121
#7  0x00007f161899bcba in QDBusConnectionManager::run (this=0x7f16189f7560 <(anonymous namespace)::Q_QGS__q_manager::innerFunction()::holder>) at /usr/src/debug/qtbase/src/dbus/qdbusconnection.cpp:179
#8  0x00007f16191b92ba in QThreadPrivate::start (arg=0x7f16189f7560 <(anonymous namespace)::Q_QGS__q_manager::innerFunction()::holder>) at thread/qthread_unix.cpp:330
#9  0x00007f1618c338fd in start_thread (arg=<optimized out>) at pthread_create.c:442
#10 0x00007f1618cb5a60 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 3 (Thread 0x7f160ebf36c0 (LWP 3805)):
#0  0x00007f1618ca80bf in __GI___poll (fds=fds@entry=0x7f160ebf2d30, nfds=nfds@entry=2, timeout=timeout@entry=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f161a50cc7d in poll (__timeout=-1, __nfds=2, __fds=0x7f160ebf2d30) at /usr/include/bits/poll2.h:39
#2  QtWaylandClient::EventThread::run (this=0x55f5b15554d0) at /usr/src/debug/qtwayland/src/client/qwaylanddisplay.cpp:208
#3  0x00007f16191b92ba in QThreadPrivate::start (arg=0x55f5b15554d0) at thread/qthread_unix.cpp:330
#4  0x00007f1618c338fd in start_thread (arg=<optimized out>) at pthread_create.c:442
#5  0x00007f1618cb5a60 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 2 (Thread 0x7f1607e236c0 (LWP 3820)):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x55f5b161b4c8) at futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x55f5b161b4c8, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at futex-internal.c:87
#2  0x00007f1618c3051f in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x55f5b161b4c8, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at futex-internal.c:139
#3  0x00007f1618c32cd0 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55f5b161b478, cond=0x55f5b161b4a0) at pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x55f5b161b4a0, mutex=0x55f5b161b478) at pthread_cond_wait.c:618
#5  0x00007f160c20399e in cnd_wait () at ../mesa-22.2.2/src/c11/impl/threads_posix.c:135
#6  0x00007f160c1b6f8c in util_queue_thread_func () at ../mesa-22.2.2/src/util/u_queue.c:287
#7  0x00007f160c2038cc in impl_thrd_routine () at ../mesa-22.2.2/src/c11/impl/threads_posix.c:67
#8  0x00007f1618c338fd in start_thread (arg=<optimized out>) at pthread_create.c:442
#9  0x00007f1618cb5a60 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 1 (Thread 0x7f1615682840 (LWP 3783)):
#0  0x00007f16191f50ce in std::__atomic_base<QtSharedPointer::ExternalRefCountData*>::load (__m=std::memory_order_relaxed, this=<optimized out>) at /usr/include/c++/12.2.0/bits/atomic_base.h:820
#1  std::atomic<QtSharedPointer::ExternalRefCountData*>::load (__m=std::memory_order_relaxed, this=<optimized out>) at /usr/include/c++/12.2.0/atomic:579
#2  QAtomicOps<QtSharedPointer::ExternalRefCountData*>::loadRelaxed<QtSharedPointer::ExternalRefCountData*> (_q_value=...) at ../../include/QtCore/../../src/corelib/thread/qatomic_cxx11.h:239
#3  QBasicAtomicPointer<QtSharedPointer::ExternalRefCountData>::loadRelaxed (this=<optimized out>) at ../../include/QtCore/../../src/corelib/thread/qbasicatomic.h:248
#4  QtSharedPointer::ExternalRefCountData::getAndRef (obj=0x55f5b189b320) at tools/qsharedpointer.cpp:1396
#5  0x000055f5af7f5927 in cloneData(QMimeData const&, QStringList, bool*) ()
#6  0x000055f5af8c3b9b in X11PlatformClipboard::updateClipboardData(X11PlatformClipboard::ClipboardData*) ()
#7  0x000055f5af8c43d6 in X11PlatformClipboard::check() ()
#8  0x00007f1619392381 in QtPrivate::QSlotObjectBase::call (a=<optimized out>, r=<optimized out>, this=<optimized out>, this=<optimized out>, r=<optimized out>, a=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:398
#9  doActivate<false> (sender=0x55f5b180eb60, signal_index=3, argv=0x7ffd1650a710) at kernel/qobject.cpp:3919
#10 0x00007f16193948df in QTimer::timeout (this=<optimized out>, _t1=...) at .moc/moc_qtimer.cpp:205
#11 0x00007f16193854c6 in QObject::event (this=0x55f5b180eb60, e=0x7ffd1650a860) at kernel/qobject.cpp:1324
#12 0x000055f5af8c369e in ?? ()
#13 0x00007f1619361b88 in QCoreApplication::notifyInternal2 (receiver=0x55f5b180eb60, event=0x7ffd1650a860) at kernel/qcoreapplication.cpp:1064
#14 0x00007f16193abd53 in QTimerInfoList::activateTimers (this=0x55f5b14fc300) at kernel/qtimerinfo_unix.cpp:643
#15 0x00007f16193ac34a in timerSourceDispatch (source=<optimized out>) at kernel/qeventdispatcher_glib.cpp:183
#16 0x00007f161870981b in g_main_dispatch (context=0x7f1610005010) at ../glib/glib/gmain.c:3444
#17 g_main_context_dispatch (context=0x7f1610005010) at ../glib/glib/gmain.c:4162
#18 0x00007f161875fec9 in g_main_context_iterate.constprop.0 (context=0x7f1610005010, block=1, dispatch=1, self=<optimized out>) at ../glib/glib/gmain.c:4238
#19 0x00007f16187080d2 in g_main_context_iteration (context=0x7f1610005010, may_block=1) at ../glib/glib/gmain.c:4303
#20 0x00007f16193ac50c in QEventDispatcherGlib::processEvents (this=0x55f5b1533550, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#21 0x00007f161935a32c in QEventLoop::exec (this=0x7ffd1650ab30, flags=...) at ../../include/QtCore/../../src/corelib/global/qflags.h:69
#22 0x000055f5af8dee4e in Scriptable::monitorClipboard() ()
#23 0x000055f5af7c6a13 in Scriptable::qt_metacall(QMetaObject::Call, int, void**) ()
#24 0x00007f161a862784 in QQmlObjectOrGadget::metacall (this=0x7ffd1650b090, type=QMetaObject::InvokeMetaMethod, index=<optimized out>, argv=<optimized out>) at /usr/src/debug/qtdeclarative/src/qml/qml/qqmlobjectorgadget.cpp:51
#25 0x00007f161a7661b7 in CallMethod (callType=QMetaObject::InvokeMetaMethod, callArgs=0x7f1604227628, engine=0x55f5b1721780, argTypes=0x0, argCount=0, returnType=43, index=<optimized out>, object=...) at /usr/src/debug/qtdeclarative/src/qml/jsruntime/qv4qobjectwrapper.cpp:1318
#26 CallPrecise (object=..., data=..., engine=engine@entry=0x55f5b1721780, callArgs=callArgs@entry=0x7f1604227628, callType=callType@entry=QMetaObject::InvokeMetaMethod) at /usr/src/debug/qtdeclarative/src/qml/jsruntime/qv4qobjectwrapper.cpp:1572
#27 0x00007f161a7681b2 in QV4::QObjectMethod::callInternal (this=<optimized out>, thisObject=<optimized out>, argv=0x7f1604227578, argc=<optimized out>) at /usr/src/debug/qtdeclarative/src/qml/jsruntime/qv4qobjectwrapper.cpp:2130
#28 0x00007f161a78e2df in QV4::Runtime::CallElement::call (engine=0x55f5b1721780, baseRef=..., index=..., argv=0x7f1604227578, argc=0) at /usr/src/debug/qtdeclarative/src/qml/jsruntime/qv4runtime.cpp:1478
#29 0x00007f161a77b1e9 in QV4::Moth::VME::interpret (frame=0x7ffd1650b4e0, engine=0x55f5b1721780, code=0x55f5b17f8285 "\030\b\334\001*\002L\003*\003\300\026\b", <incomplete sequence \320>) at /usr/src/debug/qtdeclarative/src/qml/jsruntime/qv4vme_moth.cpp:763
#30 0x00007f161a7815e4 in QV4::Moth::VME::exec (frame=<optimized out>, engine=<optimized out>) at /usr/src/debug/qtdeclarative/src/qml/jsruntime/qv4vme_moth.cpp:466
#31 0x00007f161a727720 in QV4::ArrowFunction::virtualCall (fo=<optimized out>, thisObject=<optimized out>, argv=<optimized out>, argc=<optimized out>) at /usr/src/debug/qtdeclarative/src/qml/jsruntime/qv4functionobject.cpp:528
#32 0x00007f161a72cb08 in QV4::FunctionPrototype::method_apply (b=<optimized out>, thisObject=0x7f1604227520, argv=0x7f1604227520, argc=<optimized out>) at /usr/src/debug/qtdeclarative/src/qml/jsruntime/qv4functionobject.cpp:401
#33 0x00007f161a791ba1 in QV4::Runtime::CallProperty::call (engine=0x55f5b1721780, baseRef=..., nameIndex=<optimized out>, argv=0x7f1604227520, argc=2) at /usr/src/debug/qtdeclarative/src/qml/jsruntime/qv4runtime.cpp:1448
#34 0x00007f161a77affb in QV4::Moth::VME::interpret (frame=0x7ffd1650b980, engine=0x55f5b1721780, code=0x55f5b179cbb3 "\030\006\274\001\023N\r\310\002\003\270\a\036") at /usr/src/debug/qtdeclarative/src/qml/jsruntime/qv4vme_moth.cpp:351
#35 0x00007f161a7815e4 in QV4::Moth::VME::exec (frame=<optimized out>, engine=<optimized out>) at /usr/src/debug/qtdeclarative/src/qml/jsruntime/qv4vme_moth.cpp:466
#36 0x00007f161a727720 in QV4::ArrowFunction::virtualCall (fo=<optimized out>, thisObject=<optimized out>, argv=<optimized out>, argc=<optimized out>) at /usr/src/debug/qtdeclarative/src/qml/jsruntime/qv4functionobject.cpp:528
#37 0x00007f161a6ef5b8 in QV4::FunctionObject::call (argc=0, argv=0x7f16042274d0, thisObject=<optimized out>, this=0x7f160dbe8040) at /usr/src/debug/qtdeclarative/src/qml/jsruntime/qv4functionobject_p.h:202
#38 QV4::FunctionObject::call (data=<synthetic pointer>..., this=0x7f160dbe8040) at ../../include/QtQml/5.15.6/QtQml/private/../../../../../../qtdeclarative/src/qml/jsruntime/qv4jscall_p.h:112
#39 QJSValue::callWithInstance (this=<optimized out>, instance=..., args=QList<QJSValue> (size = 0)) at /usr/src/debug/qtdeclarative/src/qml/jsapi/qjsvalue.cpp:827
#40 0x000055f5af8c7ee3 in Scriptable::call(QString const&, QJSValue*, QList<QJSValue> const&) ()
#41 0x000055f5af8e070c in Scriptable::executeArgumentsSimple(QStringList const&) ()
#42 0x000055f5af7dae60 in ClipboardClient::start(QStringList const&) ()
#43 0x00007f1619392381 in QtPrivate::QSlotObjectBase::call (a=<optimized out>, r=<optimized out>, this=<optimized out>, this=<optimized out>, r=<optimized out>, a=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:398
#44 doActivate<false> (sender=0x55f5b17e8c60, signal_index=3, argv=0x7ffd1650c040) at kernel/qobject.cpp:3919
#45 0x00007f16193948df in QTimer::timeout (this=<optimized out>, _t1=...) at .moc/moc_qtimer.cpp:205
#46 0x00007f16193854c6 in QObject::event (this=0x55f5b17e8c60, e=0x7ffd1650c190) at kernel/qobject.cpp:1324
#47 0x000055f5af8c369e in ?? ()
#48 0x00007f1619361b88 in QCoreApplication::notifyInternal2 (receiver=0x55f5b17e8c60, event=0x7ffd1650c190) at kernel/qcoreapplication.cpp:1064
#49 0x00007f16193abd53 in QTimerInfoList::activateTimers (this=0x55f5b14fc300) at kernel/qtimerinfo_unix.cpp:643
#50 0x00007f16193ac34a in timerSourceDispatch (source=<optimized out>) at kernel/qeventdispatcher_glib.cpp:183
#51 0x00007f161870981b in g_main_dispatch (context=0x7f1610005010) at ../glib/glib/gmain.c:3444
#52 g_main_context_dispatch (context=0x7f1610005010) at ../glib/glib/gmain.c:4162
#53 0x00007f161875fec9 in g_main_context_iterate.constprop.0 (context=0x7f1610005010, block=1, dispatch=1, self=<optimized out>) at ../glib/glib/gmain.c:4238
#54 0x00007f16187080d2 in g_main_context_iteration (context=0x7f1610005010, may_block=1) at ../glib/glib/gmain.c:4303
#55 0x00007f16193ac50c in QEventDispatcherGlib::processEvents (this=0x55f5b1533550, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#56 0x00007f161935a32c in QEventLoop::exec (this=0x7ffd1650c440, flags=...) at ../../include/QtCore/../../src/corelib/global/qflags.h:69
#57 0x00007f1619364e59 in QCoreApplication::exec () at ../../include/QtCore/../../src/corelib/global/qflags.h:121
#58 0x000055f5af7b9532 in main ()
```
</details>

**Comment by hluk** [comment]
I think it is fixed with the latest commit: e72b2af3dd206a46c17a76ec8623d43351905e6a
